### ISSUE TITLE
Issues when using a blank value at the start of the List

### ISSUE THREAD

**Issue by marc-gist** [ThomasDev-de/bs-select#1]
Thank you for sharing a wonderful plugin, and overhaul from the last that suffers this same issue. Unfortunately Django framework, when creating select options does this, which breaks your code:

```
<select>
  <option value selected>------</option>
  <option value="1"> One </option>
  <option value="2"> Two </option>
  <option value="3"> Three </option>
</select>

```

Notice the empty `value` in the first option that is selected.  for some reason I can't get Django to stop doing that.  your code works by replacing it with the custom note (or I can override that in django, but not the value issue).

removing the lines at 341 to 344 seems to fix it without causing any other issues that I have noticed yet.

```
// if (!value || value === "") {
//     // Ignore options without value
//     return;
// }
```

With those lines of code in, when you select an option, either searched or not, the item above it is the one that returns and is displayed.

not 100% sure what you are doing with that ignore, but seems to be ok to remove :D

Thanks again.

**Comment by ThomasDev-de** [comment]
Hey, thanks for your feedback and the detailed description. I think the exam after the value is a forgotten relic from times gone by :).  I have commented out the affected lines, as the value is checked again afterward.
Thank you very much, I hope I can close the issue with this?

**Comment by marc-gist** [comment]
so safe to leave out those lines! great thanks!  most of the time value has something, or is left out, seemed to work with the value set, but I couldn't for the life of me figure out how to get django to do that lol :)
