### ISSUE TITLE
Disable Select

### ISSUE THREAD

**Issue by marc-gist** [ThomasDev-de/bs-select#2]
I can't seem to get the disable to work. I can still make changes to the select.
I set both the `disable` and class
```
<select name="blah" disabled class="blah disabled"> ... </select>
```

Ideas? Thanks!

**Comment by marc-gist** [comment]
I modified your code to pass in the select field to the `onBeforeChange`, and used the css class. seems to work :)
```
function changeSelect(select) {
        let obj = $(select);
        console.log(obj);
        return !obj.hasClass('isDisabled');
    }
```

**Comment by ThomasDev-de** [comment]
Hi, yes I noticed that too, just haven't had time to test everything thoroughly yet. I made a small change which disables all options if the select has the class disabled.

Let me know if it works now.
