### ISSUE TITLE
how do I update the options?

### ISSUE THREAD

**Issue by emailagency** [ThomasDev-de/bs-select#4]
Hi!

I see there is a updateOptions and not sure how to work it. 

I'm trying to remove and refill the options via a function. Basically, when another field is selected, I will have this field update it's options based on what's selected in the first drop down. 

Any way you could help me with just the JS to:

1. clear all options and then 
2. rebuild the options without having to redo the select and calling bsSelect again. 

I'll shoot you a coffee, just drop me a PP link :)

**Comment by ThomasDev-de** [comment]
Hello,

the updateOptions method is only used to update the plugin options (e.g. the color of the dropdown).
To fill a second select with option-tags based on the selection of the first select, intercept the change.bs.select and fill the second select with javascript. When the second select is filled, you can update it using the refresh method.
I have placed an example in the demo/examples/ directory.
Have I understood you correctly?

**Comment by emailagency** [comment]
Thank you so much, I have it working.
