### ISSUE TITLE
bsTheme

### ISSUE THREAD

**Issue by markocrni** [ThomasDev-de/bs-select#5]
Lost 2 hours to determine why select is not reacting to my theme variables:
```
const hasTheme = $select.data('bsTheme') || $select.closest('[data-bs-theme]').length > 0;
....
if (hasTheme){
    $dropdown.attr('data-bs-theme', $select.data('bsTheme') || $select.closest('[data-bs-theme]').data('bsTheme'));
}
```

And then you get
`<div class="js-bs-select-dropdown" data-bs-theme="dark" style="width: 100%;">`

Which references to bootstrap colors... (vars)
Why there is need to inject data-bs-theme in this div?!

**Comment by ThomasDev-de** [comment]
You are absolutely right. the data-bs-theme attribute on the dropdown is superfluous. sorry for your loss of time. Was removed in v1.0.2
